repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff linting
        entry: uv run ruff check --fix
        language: system
        types: [python]
        pass_filenames: false
      - id: ruff-format
        name: ruff formatting
        entry: uv run ruff format
        language: system
        types: [python]
        pass_filenames: false
