version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.12"
  commands:
    - pip install uv
    - uv run --group docs sphinx-build docs $READTHEDOCS_OUTPUT/html -b html -W

sphinx:
  configuration: docs/conf.py
